on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello World > HELLO-WORLD.txt
      - name: Run the Docker Action
        uses: ./
      - name: Inspect folder
        run: ls -al .
      - name: Inspect LIST.txt
        run: cat LIST.txt
